// panel-react/src/components/rightbar/Toolbar.js
import React, { useState } from "react";
import { AssetsFolder } from "./components/AssetsFolder";
import { DesignPanel } from "./components/DesignPanel";

const tabs = [
    { name: 'Design', id: 'design' },
    { name: 'Assets', id: 'assets' }
];

export const Toolbar = () => {
    const [activeTab, setActiveTab] = useState(tabs[0].id);

    return (
        <div className="w-full h-full">
            <div className="flex text-xs">
                <button className={`flex justify-center items-center w-1/2 py-1 rounded-t-lg cursor-pointer
                ${activeTab == 'design' ? 'bg-gray-100' : ''}`} onClick={() => setActiveTab('design')}>DESIGN</button>
                <button className={`flex justify-center items-center w-1/2 py-1 rounded-t-lg cursor-pointer
                ${activeTab == 'assets' ? 'bg-gray-100' : ''}`} onClick={() => setActiveTab('assets')}>ASSETS</button>
            </div>
            <div className="w-full h-full bg-gray-100">
                {activeTab == 'design' ? <AssetsFolder /> : <DesignPanel /> }
            </div>
        </div>
    )
}

// panel/src/lib/rightbar/ToolBar.svelte
<script>
    import AssetsFolder from "./components/AssetsFolder.svelte";
    import DesignPanel from "./components/DesignPanel.svelte";

    let activeTab = 'design';

    let tabs = [
        { name: 'Design', id: 'design' },
        { name: 'Assets', id: 'assets' }
    ];

    const setActiveTab = (tab) => {
        activeTab = tab;
    };
</script>

<div class="w-full h-full">
    <div class="flex text-xs">
        <button class={`flex justify-center items-center w-1/2 py-1 rounded-t-lg cursor-pointer
        ${activeTab == 'design' ? 'bg-gray-100' : ''}`} on:click={() => setActiveTab('design')}>DESIGN</button>
        <button class={`flex justify-center items-center w-1/2 py-1 rounded-t-lg cursor-pointer
        ${activeTab == 'assets' ? 'bg-gray-100' : ''}`} on:click={() => setActiveTab('assets')}>ASSETS</button>
    </div>
    <div class="w-full h-full bg-gray-100">
        <!-- CONTENT -->
        {#if activeTab == 'assets'}<AssetsFolder />{/if}
        {#if activeTab == 'design'}<DesignPanel />{/if}
    </div>
</div>
